name = "ladder-001"
main = "_worker.js"
compatibility_date = "2025-11-04"
keep_vars = true

[[kv_namespaces]]
binding = "KV"			#KV绑定名默认不可修改
id = "a18aa03aa43941f781605fd8ededae91"				#KV数据库id
